import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import { Poppins, Be_Vietnam_Pro } from "next/font/google";
import { Providers } from "./provider";
import { ThemeProvider } from "@/utils/next-theme";
import Custom from "@/utils/custom";

import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-Poppins",
});

const beVietnamPro = Be_Vietnam_Pro({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-Be-VietNam-Pro",
});

export const metadata: Metadata = {
  title: "Wowi Test",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${beVietnamPro.variable} ${poppins.variable}`}>
        <Providers>
          <ThemeProvider attribute="class" defaultTheme="light">
            <ToastContainer />
            <Custom>{children}</Custom>
          </ThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
